import os
import sys
import subprocess
picard="/software/picard/picard.jar"
ref="/data/Database/hg19/ucsc.hg19.fasta"
def run(bed,bam,outdir,prefix):
    if not os.path.exists(outdir):
        os.mkdir(outdir)
    out=outdir+"/"+prefix
    ####BedToIntervalList (Picard)#############
    cmd="java -jar %s BedToIntervalList I=%s O=%s.interval_list SD=%s" %(picard,bed,out,bam)
    subprocess.check_call(cmd,shell=True)
    ####Metrics generated by CollectHsMetrics for the analysis of target-capture sequencing experiments#######
    cmd="java -jar %s CollectHsMetrics I=%s O=%s.hs_metrics.txt R=%s TARGET_INTERVALS=%s.interval_list" \
        "COVMAX=null SAMPLE_SIZE=null "%(picard,bam,out,ref,out)
    subprocess.check_call(cmd,shell=True)

if __name__=="__main__":
    if (len(sys.argv)!=5):
        print("\nUsage:python3 %s bedfile bamfile outdir prefix"%(sys.argv[0]))
        print("\nEmail:fanyucai1@126.com")
    else:
        bed=sys.argv[1]
        bam=sys.argv[2]
        outdir=sys.argv[3]
        prefix=sys.argv[4]
        run(bed,bam,outdir,prefix)
